apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-delete-tasks-api
  namespace: delete-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-delete-tasks-api
  template:
    metadata:
      labels:
        app: todo-delete-tasks-api
    spec:
      containers:
        - name: todo-delete-tasks-api
          image: acrdigwimicrotodoappdev.azurecr.io/todo-delete-tasks-api:v1
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
